---
title: "Programa de Prevención & Control del Dengue |2025"
format: 
  dashboard:
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup_30_veracruz}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        #platform = "mapdeck",
                        basemaps.color.shuffle = FALSE)
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
load("/Users/fdzul/Documents/geocoding_mx/8.RData/denmex_2025.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("D:\\OneDrive\\proyects\\geocoding_mex\\2024\\8.RData\\denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    load("/home/fdzul/Documents/active_transmission/geocoding_mx/8.RData/denmex_2025.RData")
}
library(magrittr)
#mapviewOptions(platform = "mapdeck")
```



# [**Cadenas de Transmisión**]{style="font-size:8pt"}

::: panel-tabset

### [**Veracruz**]{style="color:#990000"}

```{r chains_veracruz}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "30",
                                     locality = c("Veracruz", "Boca del Rio"),
                                     dengue_cases = "Probable")
```


### [**Xalapa**]{style="color:#990000"}

```{r chains_xalapa}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "30",
                                     locality = "Xalapa de Enriquez",
                                     dengue_cases = "Probable")
```




:::



# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Veracruz**]{style="color:#990000"}

```{r heatmap_veracruz}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "30",
                   locality = "Veracruz",
                   status_caso = c(1, 2),
                   kernel = 400, 
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```


### [**Xalapa**]{style="color:#990000"}

```{r heatmap_xalapa}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "30",
                   locality = "Xalapa de Enriquez",
                   status_caso = c(1, 2),
                   kernel = 400,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```

### [**Coatzacoalcos**]{style="color:#990000"}

```{r heatmap_coatza}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "30",
                   locality = c("Coatzacoalcos",
                                "Puerto Esmeralda"),
                   status_caso = c(1, 2),
                   kernel = 000,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```


### [**Poza Rica de Hidalgo**]{style="color:#990000"}

```{r heatmap_poza}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "30",
                   locality = "Poza Rica de Hidalgo",
                   status_caso = c(1, 2),
                   kernel = 000,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```


### [**Tuxpam de Rodriguez Cano**]{style="color:#990000"}

```{r heatmap_tuxpan}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "30",
                   locality = "Tuxpan de Rodriguez Cano",
                   status_caso = c(1, 2),
                   kernel = 000,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```



:::


